INSERT INTO contact (street, city_id) VALUES ('Rua tal', 280);
INSERT INTO contact (street, city_id) VALUES ('Rua tal 1', 280);
INSERT INTO contact (street, city_id) VALUES ('Rua tal 2', 200);
INSERT INTO contact (street, city_id) VALUES ('Rua tal 3', 12);
INSERT INTO contact (street, city_id) VALUES ('Rua tal 4', 67);
INSERT INTO contact (street, city_id) VALUES ('Rua tal 5', 289);
INSERT INTO contact (street, city_id) VALUES ('Rua tal 6', 267);
INSERT INTO contact (street, city_id) VALUES ('Rua tal 7', 223);
INSERT INTO contact (street, city_id) VALUES ('Rua tal 8', 223);
INSERT INTO contact (street, city_id) VALUES ('Rua tal 9', 25);
INSERT INTO contact (street, city_id) VALUES ('Rua tal 10', 28);